apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml


patchesStrategicMerge:
- overlays/production/argo-cd-cm.yaml

patchesJson6902:
- path: overlays/production/argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

namespace: argocd

images:
- name: quay.io/argoproj/argocd
  newName: docker.pkg.github.com/argoproj/argo-cd/argocd
  newTag: 1.9.0-73edc0a6
